import { useParams } from "react-router-dom";
import { motion } from "framer-motion";
import CornerFrame from "../components/hud/CornerFrame";
import StatusPill from "../components/StatusPill";

export default function ReportViewer() {
  const { scanId } = useParams();

  return (
    <div className="mx-auto max-w-4xl px-6 pb-24 pt-32">
      <motion.p
        initial={{ opacity: 0, y: 8 }}
        animate={{ opacity: 1, y: 0 }}
        className="font-mono text-xs uppercase tracking-[0.3em] text-amber/70"
      >
        Forensic Report
      </motion.p>
      <motion.h1
        initial={{ opacity: 0, y: 12 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.05 }}
        className="mt-2 font-display text-4xl font-semibold sm:text-5xl"
      >
        Scan {scanId}
      </motion.h1>
      <motion.p
        initial={{ opacity: 0, y: 12 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.1 }}
        className="mt-3 font-mono text-xs text-bone/30"
      >
        Layout preview — populated once the scan pipeline returns a fused verdict for this scan ID.
      </motion.p>

      <motion.div
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.15 }}
        className="mt-10 grid gap-6 sm:grid-cols-[1fr_1fr]"
      >
        <CornerFrame className="p-6">
          <p className="font-mono text-[10px] uppercase tracking-widest text-bone/40">Fused Verdict</p>
          <div className="mt-3">
            <StatusPill score={0} label="Pending" />
          </div>
          <div className="mt-6 flex flex-col gap-3">
            {["Visual", "Audio", "Lip-Sync"].map((m) => (
              <div key={m} className="flex items-center justify-between border-b border-line pb-2 font-mono text-xs">
                <span className="text-bone/50">{m}</span>
                <span className="text-bone/20">—</span>
              </div>
            ))}
          </div>
        </CornerFrame>

        <CornerFrame className="flex flex-col items-center justify-center gap-3 p-6">
          <p className="self-start font-mono text-[10px] uppercase tracking-widest text-bone/40">Grad-CAM Heatmap</p>
          <div className="flex h-40 w-full items-center justify-center border border-dashed border-line-bright font-mono text-[10px] uppercase tracking-widest text-bone/20">
            No frame selected
          </div>
        </CornerFrame>

        <CornerFrame className="p-6 sm:col-span-2">
          <p className="font-mono text-[10px] uppercase tracking-widest text-bone/40">Narrative Explanation</p>
          <p className="mt-3 font-mono text-sm leading-relaxed text-bone/30">
            Generated by Claude once the fusion stage completes — walks through which signals drove the verdict in plain language.
          </p>
        </CornerFrame>
      </motion.div>
    </div>
  );
}
